// 🤖 This file is auto-generated by scripts/generate-routes.js
// Do not edit manually - it will be overwritten
// Add new pages by creating .jsx files in this directory with route exports

// Named exports for direct imports
export { default as About, route as aboutRoute } from './About';
export { default as Contact, route as contactRoute } from './Contact';
export { default as Home, route as homeRoute } from './Home';
export { default as Services, route as servicesRoute } from './Services';

// Import components and their route configurations
import About, { route as aboutRoute } from './About';
import Contact, { route as contactRoute } from './Contact';
import Home, { route as homeRoute } from './Home';
import Services, { route as servicesRoute } from './Services';

/**
 * Centralized route configuration
 * Automatically built from page components in this directory
 * Similar to Next.js pages directory or SvelteKit routes
 * 
 * To add a new route:
 * 1. Create a new .jsx file in src/pages (e.g., Services.jsx)
 * 2. Export your component as default
 * 3. Export a route object with path and meta properties
 * 4. Run the dev server - the route will be automatically picked up
 * 
 * Example:
 * export const route = {
 *   path: '/services',
 *   meta: { title: 'Our Services' }
 * };
 * export default Services;
 */
export const routes = [
  {
    ...aboutRoute,
    component: About
  },
  {
    ...contactRoute,
    component: Contact
  },
  {
    ...homeRoute,
    component: Home
  },
  {
    ...servicesRoute,
    component: Services
  }
];
