/**
 * Automatic Route Generation Script
 * Scans the pages directory and generates route configuration automatically
 * Similar to Next.js file-based routing
 */

const fs = require('fs');
const path = require('path');

const PAGES_DIR = path.join(__dirname, '../src/pages');
const OUTPUT_FILE = path.join(PAGES_DIR, 'index.js');

/**
 * Get all page files from the pages directory
 * Excludes index.js, .css files, and non-.jsx files
 */
function getPageFiles() {
  const files = fs.readdirSync(PAGES_DIR);
  
  return files
    .filter(file => {
      // Only include .jsx files
      if (!file.endsWith('.jsx')) return false;
      // Exclude any files that start with underscore (private components)
      if (file.startsWith('_')) return false;
      return true;
    })
    .map(file => {
      const name = file.replace('.jsx', '');
      return {
        filename: file,
        name,
        importName: name,
        routeName: `${name.toLowerCase()}Route`
      };
    });
}

/**
 * Generate the routes index file
 */
function generateRoutesFile() {
  const pages = getPageFiles();
  
  if (pages.length === 0) {
    console.warn('⚠️  No page files found in src/pages directory');
    return;
  }

  // Generate imports
  const imports = pages.map(page => 
    `import ${page.importName}, { route as ${page.routeName} } from './${page.name}';`
  ).join('\n');

  // Generate named exports
  const namedExports = pages.map(page =>
    `export { default as ${page.importName}, route as ${page.routeName} } from './${page.name}';`
  ).join('\n');

  // Generate routes array
  const routesArray = pages.map(page => `  {
    ...${page.routeName},
    component: ${page.importName}
  }`).join(',\n');

  // Generate the complete file
  const content = `// 🤖 This file is auto-generated by scripts/generate-routes.js
// Do not edit manually - it will be overwritten
// Add new pages by creating .jsx files in this directory with route exports

// Named exports for direct imports
${namedExports}

// Import components and their route configurations
${imports}

/**
 * Centralized route configuration
 * Automatically built from page components in this directory
 * Similar to Next.js pages directory or SvelteKit routes
 * 
 * To add a new route:
 * 1. Create a new .jsx file in src/pages (e.g., Services.jsx)
 * 2. Export your component as default
 * 3. Export a route object with path and meta properties
 * 4. Run the dev server - the route will be automatically picked up
 * 
 * Example:
 * export const route = {
 *   path: '/services',
 *   meta: { title: 'Our Services' }
 * };
 * export default Services;
 */
export const routes = [
${routesArray}
];
`;

  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
  
  console.log(`✅ Generated routes for ${pages.length} page(s):`);
  pages.forEach(page => {
    console.log(`   - ${page.name}`);
  });
}

// Run the generator
try {
  generateRoutesFile();
} catch (error) {
  console.error('❌ Error generating routes:', error);
  process.exit(1);
}
